export const ACTION_ADD_CREATE = "ACTION_ADD_CREATE";
export const ACTION_ADD_DELETE = "ACTION_ADD_DELETE";
export const ACTION_ADD_UPDATE = "ACTION_ADD_UPDATE";
export const ACTION_START_RECORDING = "ACTION_START_RECORDING";
export const ACTION_STOP_RECORDING = "ACTION_STOP_RECORDING";
