export const IS_RECORDING = "IS_RECORDING";
export const NOT_RECORDING = "NOT_RECORDING";
export const ACTION_CREATE = "ACTION_CREATE";
export const ACTION_DELETE = "ACTION_DELETE";
export const ACTION_UPDATE = "ACTION_UPDATE";
export const REMOVE_TOP = "REMOVE_TOP";
